site_name: classyclick

nav:
  - Contents:
    - Library: README.md
  - Project Links:
    - Github: https://github.com/fopina/classyclick/
    - PyPI: https://test.pypi.org/project/classyclick/

theme:
  name: readthedocs

