site_name: classyclick

nav:
  - Home: README.md
  - Guide: guide.md
  - API Reference: api.md
  - Project Links:
    - Github: https://github.com/fopina/classyclick/
    - PyPI: https://pypi.org/project/classyclick/

theme:
  name: readthedocs
