name: 🧪 tests

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
  push:
    branches-ignore:
      # these are already tested by publish-dev
      - dev
      - dev/*
      - dev-*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Lint check
        run: |
          make lint-check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.10 added as there are "unique" issues in it (such as Path requiring str() for many core methods)
        python-version: ['3.9', '3.10', '3.12', '3.13']
        click-version: ['==7.0', '>8']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev
      
      - name: Install click ${{ matrix.click-version }}
        run: |
          uv run pip install --upgrade "click${{ matrix.click-version }}"

      - name: Run unit tests
        run: |
          make test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
